services:
  mongodb:
    image: mongo:7
    container_name: daily-report-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: daily_reports
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

  localstack:
    image: localstack/localstack:latest
    container_name: daily-report-localstack
    environment:
      SERVICES: s3
      DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
    ports:
      - '4566:4566'
    volumes:
      - localstack_data:/var/lib/localstack

  elasticmq:
    image: softwaremill/elasticmq:latest
    container_name: daily-report-elasticmq
    ports:
      - '9324:9324'
      - '9325:9325'
    volumes:
      - ./elasticmq.conf:/opt/elasticmq.conf

volumes:
  mongodb_data:
  localstack_data:
